const mongoose = require("mongoose");

const privateMessagesSchema = new mongoose.Schema({
    // Id field is automatically generated by MongoDB
    private_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Private", // Reference to the "Private" model
        required: [true,"Private Id is required"]
    },
    user_send: {
        type: String,
        required: [true,"User Send is required"]
    },
    message: {
        type: String,
        required: true,
        required: [true,"Message is required"]
    },
    reply_to:{
        type: mongoose.Schema.Types.ObjectId,
        ref: "PrivateMessage",
        required:false,
    },
    reply_message_to:{
        type: String,
        required: false,
    }
},
    {
        timestamps: true,
    }
);

// Create the Private model
module.exports = mongoose.model("PrivateMessage", privateMessagesSchema);

